### ISSUE TITLE
Receive request was banned

### ISSUE THREAD

**Issue by GaryDu0123** [shuyangzhang/bilibili_proxy#1]
![image](https://github.com/shuyangzhang/bilibili_proxy/assets/66729711/7145b897-b1fb-4248-bb35-a09be842b0b6)

Im not sure if this is a widespread issue, but I solved this problem by adding the User-Agent to the header.

see https://github.com/GaryDu0123/bilibili_proxy/commit/1d6d969de8eb0aadf2e5ba05c6b9f925d9f46e51

**Comment by GaryDu0123** [comment]
```
2024-05-24 17:49:27.820 | ERROR    | app.task.interval_tasks:keep_bproxy_alive:98 - bproxy is not alive now
2024-05-24 17:49:30.124 | INFO     | app.utils.log_utils:wrapped_function:12 - user: Gary user_id: 1228020826 in guild_id: 2691112685935799 used command bilibili with args ('[https://www.bilibili.com/video/BV1os421P7ad/?spm_id_from=333.1007.top_right_bar_window_default_collection.content.click&vd_source=0d1c4a0fa7876764befbd0323283cc53](https://www.bilibili.com/video/BV1os421P7ad/?spm_id_from=333.1007.top_right_bar_window_default_collection.content.click&vd_source=0d1c4a0fa7876764befbd0323283cc53)',) and {}, log_id: 87d52783-ff35-447b-aa4c-73e07e58bc8c
2024-05-24 17:49:30.358 | ERROR    | app.utils.log_utils:wrapped_function:18 - error occurred, msg: request was banned, log_id: 87d52783-ff35-447b-aa4c-73e07e58bc8c, traceback: Traceback (most recent call last):
  File "/Kyouka/app/utils/log_utils.py", line 16, in wrapped_function
    await func(msg, *args, **kwargs)
  File "/Kyouka/app/utils/permission_utils.py", line 20, in wrapped_function
    await func(msg, *args, **kwargs)
  File "/Kyouka/app/utils/permission_utils.py", line 10, in wrapped_function
    await func(msg, *args, **kwargs)
  File "/Kyouka/app/main.py", line 211, in play_audio_from_bilibili_video
    result = await bvid_to_music_by_local_bproxy(BVid=BVid)
  File "/Kyouka/app/music/bilibili/search.py", line 105, in bvid_to_music_by_local_bproxy
    ret = await bvid_to_music(BVid=BVid)
  File "/Kyouka/app/music/bilibili/search.py", line 70, in bvid_to_music
    matched, name, author, cid, duration, cover_image_url = await fetch_basic_video_info_by_BVid(BVid=BVid)
  File "/Kyouka/app/music/bilibili/search.py", line 22, in fetch_basic_video_info_by_BVid
    raise Exception(resp_json.get("message", "fetch video info failed, unknown reason."))
Exception: request was banned

2024-05-24 17:49:31.507 | DEBUG    | app.task.interval_tasks:update_played_time_and_change_music:15 - PLAYED: 0
2024-05-24 17:49:31.507 | DEBUG    | app.task.interval_tasks:update_played_time_and_change_music:16 - Q: []
2024-05-24 17:49:31.507 | DEBUG    | app.task.interval_tasks:update_played_time_and_change_music:17 - LOCK: False

```
logs from bproxy here
